### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChrisDelClea** [giswqs/streamlit-timeline#3]
Hey @giswqs ,

really cool component. Quick question:
Could one combine the timeline with a linechart. So instead of having boxes
one would have just a linechart? So i could also have along the y-axis groups 
and for each group i would get a linechart in the x-axis along the time?

**Comment by giswqs** [comment]
Check out the examples at https://visjs.github.io/vis-timeline/examples/timeline/. If you can find a solution there, it should be feasible with this streamlit component as well.

**Comment by ChrisDelClea** [comment]
I actually found the page too but no solution for my problem. Do you know the difference between graph2d and timeline and how to combine them?

**Comment by ChrisDelClea** [comment]
Can i somehow set the default focus not to hours but days?

**Comment by giswqs** [comment]
I am not really a JavaScript user. I think you can look at the Configuration Options, `zoomMin`, `ZoomMax`, `hiddenDates`, etc. 

https://visjs.github.io/vis-timeline/docs/timeline/#items

**Comment by ChrisDelClea** [comment]
Thanks
