### ISSUE TITLE
Frontend build files don't exist

### ISSUE THREAD

**Issue by marcjulianschwarz** [giswqs/streamlit-timeline#5]
Hi @giswqs,

it looks like the newest version of streamlit-vis-timeline on PyPI doesn't include the frontend build files.
The prior version 0.2.0 works just fine (but still includes the streamlit st.cache deprecation warning).

<img width="729" alt="Bildschirm­foto 2023-02-21 um 18 23 09" src="https://user-images.githubusercontent.com/67844154/220416098-0596bdad-e57c-4158-9b3b-646cfcbf0d5d.png">

**Comment by giswqs** [comment]
Thank you for reporting. It should be fixed now. 

https://pypi.org/project/streamlit-vis-timeline/0.3.0/#files

**Comment by marcjulianschwarz** [comment]
Thank you :)
